import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/Navbar";
import { config } from "@fortawesome/fontawesome-svg-core";
import { CartProvider } from "./CartContext";
config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CloudMall",
  description: "Generated by Matthew Ameh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <CartProvider>
            <div className="overflow-y-auto flex-grow">{children}</div>
          </CartProvider>
        </div>
      </body>
    </html>
  );
}
