import { Inter } from "next/font/google";
import "./globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { CartProvider } from "./(components)/CartContext";

config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CloudMall",
  description: "Generated by Matthew Ameh",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen max-h-screen">
          <div className="overflow-y-auto flex-grow">
            {" "}
            <CartProvider>{children}</CartProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
