const products = [
  {
    id: 1,
    name: "Fresh Kale Greens",
    price: 2000,
    discountedPrice: 3000,
    discount: 12,
    image: "pngwing.com (12).png",
  },

  {
    id: 3,
    name: "Herb Infused Olive Oil",
    price: 10000,
    discountedPrice: 13000,
    discount: 8,
    image: "pngwing.com (19).png",
  },
  {
    id: 4,
    name: "Farm-Fresh Tomatoes",
    price: 6000,
    discountedPrice: 8200,
    discount: 10,
    image: "pngwing.com (16).png",
  },

  {
    id: 5,
    name: "Organic Zucchini Squash",
    price: 2000,
    discountedPrice: 3000,
    discount: 12,
    image: "pngwing.com (17).png",
  },

  {
    id: 7,
    name: "Garden Fresh Eggplants",
    price: 5000,
    discountedPrice: 7000,
    discount: 12,
    image: "pngwing.com (21).png",
  },
  {
    id: 8,
    name: "Fresh Grape",
    price: 7000,
    discountedPrice: 9000,
    discount: "New",
    image: "pngwing.com (44).png",
  },

  {
    id: 10,
    name: "Farm-Fresh Watermelon",
    price: 7000,
    discountedPrice: 10000,
    discount: 12,
    image: "pngwing.com (43).png",
  },
  {
    id: 11,
    name: "Cantaloupe Melon",
    price: 4000,
    discountedPrice: 7000,
    discount: "New",
    image: "pngwing.com (22).png",
  },
  {
    id: 12,
    name: "Chobani Greek Cuisine",
    price: 750,
    discountedPrice: 1500,
    discount: 12,
    image: "1.png",
  },
  {
    id: 13,
    name: "Chinese Steamed Eggs",
    price: 7000,
    discountedPrice: 9500,
    discount: 12,
    image: "2.png",
  },
  {
    id: 14,
    name: "Fresh Honey Jar",
    price: 2000,
    discountedPrice: 3500,
    discount: 12,
    image: "3.png",
  },
  {
    id: 15,
    name: "Healthy Yellow Banana",
    price: 2000,
    discountedPrice: 3500,
    discount: 12,
    image: "4.png",
  },
  {
    id: 16,
    name: "Fresh Pineapple",
    price: 3000,
    discountedPrice: 3500,
    discount: 12,
    image: "6.png",
  },
  {
    id: 17,
    name: "Non-fat Soya Milk",
    price: 1200,
    discountedPrice: 2500,
    discount: 6,
    image: "7.png",
  },
  {
    id: 18,
    name: "Honeycrisp Apples",
    price: 2000,
    discountedPrice: 3500,
    discount: 2,
    image: "8.png",
  },
  {
    id: 19,
    name: "Smoothie Spinach Leaf",
    price: 7000,
    discountedPrice: 10000,
    discount: 12,
    image: "9.png",
  },
  {
    id: 20,
    name: "Celery Vegetable",
    price: 1200,
    discountedPrice: 1800,
    discount: 12,
    image: "10.png",
  },
  {
    id: 21,
    name: "Cabbage Cauliflower",
    price: 2000,
    discountedPrice: 3500,
    discount: 7,
    image: "12.png",
  },
  {
    id: 22,
    name: "Peperoncino Chili",
    price: 2000,
    discountedPrice: 3500,
    discount: 12,
    image: "13.png",
  },
  {
    id: 23,
    name: "Cucumber",
    price: 1000,
    discountedPrice: 1500,
    discount: 5,
    image: "14.png",
  },
  {
    id: 24,
    name: "Cantaloupe Melon",
    price: 3000,
    discountedPrice: 6500,
    discount: 5,
    image: "5.png",
  },
  {
    id: 25,
    name: "Fresh Lemon",
    price: 800,
    discountedPrice: 1500,
    discount: 4,
    image: "15.png",
  },
  {
    id: 26,
    name: "Smoothie Berry",
    price: 2000,
    discountedPrice: 2500,
    discount: 13,
    image: "16.png",
  },
  {
    id: 27,
    name: "Grapes",
    price: 5000,
    discountedPrice: 6500,
    discount: 9,
    image: "17.png",
  },
  {
    id: 28,
    name: "White Rice Cereal",
    price: 7000,
    discountedPrice: 8500,
    discount: 10,
    image: "18.png",
  },
];

export default products