const products = [
  {
    id: 1,
    name: "Fresh Kale Greens",
    price: 2000,
    discountedPrice: 3000,
    discount: 12,
    image: "pngwing.com (12).png",
  },
  {
    id: 2,
    name: "Sweet Bell Hami Mix",
    price: 4000,
    discountedPrice: 6000,
    discount: 10,
    image: "pngwing.com (14).png",
  },
  {
    id: 3,
    name: "Herb Infused Olive Oil",
    price: 10000,
    discountedPrice: 13000,
    discount: 8,
    image: "pngwing.com (19).png",
  },
  {
    id: 4,
    name: "Farm-Fresh Tomatoes",
    price: 6000,
    discountedPrice: 8200,
    discount: 10,
    image: "pngwing.com (16).png",
  },

  {
    id: 5,
    name: "Organic Zucchini Squash",
    price: 2000,
    discountedPrice: 3000,
    discount: 12,
    image: "pngwing.com (17).png",
  },
  {
    id: 6,
    name: "Organic Baby Spinach",
    price: 5000,
    discountedPrice: 7000,
    discount: 12,
    image: "pngwing.com (13).png",
  },
  {
    id: 7,
    name: "Garden Fresh Eggplants",
    price: 5000,
    discountedPrice: 7000,
    discount: 12,
    image: "pngwing.com (21).png",
  },
  {
    id: 8,
    name: "Fresh Grape",
    price: 7000,
    discountedPrice: 9000,
    discount: "New",
    image: "pngwing.com (44).png",
  },
  {
    id: 9,
    name: "Organic Baby Spinach",
    price: 5000,
    discountedPrice: 7000,
    discount: 12,
    image: "pngwing.com (13).png",
  },
  {
    id: 10,
    name: "Farm-Fresh Watermelon",
    price: 7000,
    discountedPrice: 10000,
    discount: 12,
    image: "/images/farm-fresh-watermelon.png",
  },
  {
    id: 11,
    name: "Cantaloupe Melon",
    price: 4000,
    discountedPrice: 7000,
    discount: "New",
    image: "/images/cantaloupe-melon.png",
  },
  {
    id: 12,
    name: "Chobani Greek Cuisine",
    price: 750,
    discountedPrice: 1500,
    discount: 12,
    image: "/images/chobani-greek-cuisine.png",
  },
  {
    id: 13,
    name: "Chinese Steamed Eggs",
    price: 7000,
    discountedPrice: 9500,
    discount: 12,
    image: "/images/chinese-steamed-eggs.png",
  },
  {
    id: 14,
    name: "Fresh Honey Jar",
    price: 2000,
    discountedPrice: 3500,
    discount: 12,
    image: "/images/fresh-honey-jar.png",
  },
  {
    id: 15,
    name: "Healthy Yellow Banana",
    price: 2000,
    discountedPrice: 3500,
    discount: 12,
    image: "/images/healthy-yellow-banana.png",
  },
  {
    id: 16,
    name: "Fresh Pineapple",
    price: 3000,
    discountedPrice: 3500,
    discount: 12,
    image: "/images/fresh-pineapple.png",
  },
  {
    id: 17,
    name: "Non-fat Soya Milk",
    price: 1200,
    discountedPrice: 2500,
    discount: 6,
    image: "/images/non-fat-soya-milk.png",
  },
  {
    id: 18,
    name: "Honeycrisp Apples",
    price: 2000,
    discountedPrice: 3500,
    discount: 2,
    image: "/images/honeycrisp-apples.png",
  },
  {
    id: 19,
    name: "Smoothie Spinach Leaf",
    price: 7000,
    discountedPrice: 10000,
    discount: 12,
    image: "/images/smoothie-spinach-leaf.png",
  },
  {
    id: 20,
    name: "Celery Vegetable",
    price: 1200,
    discountedPrice: 1800,
    discount: 12,
    image: "/images/celery-vegetable.png",
  },
  {
    id: 21,
    name: "Cabbage Cauliflower",
    price: 2000,
    discountedPrice: 3500,
    discount: 7,
    image: "/images/cabbage-cauliflower.png",
  },
  {
    id: 22,
    name: "Peperoncino Chili",
    price: 2000,
    discountedPrice: 3500,
    discount: 12,
    image: "/images/peperoncino-chili.png",
  },
  {
    id: 23,
    name: "Cucumber",
    price: 1000,
    discountedPrice: 1500,
    discount: 5,
    image: "/images/cucumber.png",
  },
  {
    id: 24,
    name: "Cantaloupe Melon",
    price: 3000,
    discountedPrice: 6500,
    discount: 5,
    image: "/images/cantaloupe-melon.png",
  },
  {
    id: 25,
    name: "Fresh Lemon",
    price: 800,
    discountedPrice: 1500,
    discount: 4,
    image: "/images/fresh-lemon.png",
  },
  {
    id: 26,
    name: "Smoothie Berry",
    price: 2000,
    discountedPrice: 2500,
    discount: 13,
    image: "/images/smoothie-berry.png",
  },
  {
    id: 27,
    name: "Grapes",
    price: 5000,
    discountedPrice: 6500,
    discount: 9,
    image: "/images/grapes.png",
  },
  {
    id: 28,
    name: "White Rice Cereal",
    price: 7000,
    discountedPrice: 8500,
    discount: 10,
    image: "/images/white-rice-cereal.png",
  },
];

export default products